# Generated by Django 2.0.7 on 2018-07-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('certification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('교필', '교양필수'), ('교선', '교양선택'), ('기전', '기본전공'), ('선전', '선택전공'), ('응전', '응용전공'), ('계필', '계열필수')], max_length=25)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrawler.Major')),
            ],
        ),
    ]
