# Generated by Django 2.0.7 on 2018-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
