# Generated by Django 2.0.7 on 2018-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0002_subject_subject_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
