# Generated by Django 2.0.7 on 2018-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0003_subject_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='type',
            new_name='subject_type',
        ),
        migrations.AddField(
            model_name='subject',
            name='certification_type',
            field=models.CharField(choices=[('인필전', '인필전'), ('인선전', '인선전')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
