# Generated by Django 2.0.7 on 2018-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0004_auto_20180715_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='necessary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='certification_type',
            field=models.CharField(choices=[('인필교', '인필교'), ('인선교', '인선교'), ('인선전', '인선전'), ('인필전', '인선전'), ('인필BSM', '인필BSM')], max_length=25),
        ),
    ]
