# Generated by Django 2.0.7 on 2018-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0006_auto_20180718_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='major',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ManyToManyField(to='webcrawler.Major'),
        ),
    ]
