# Generated by Django 2.0.7 on 2018-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0007_auto_20180718_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='point',
            new_name='subject_point',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_detail_major',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_theory',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_training',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('교필', '교양필수'), ('교선', '교양선택'), ('기전', '기본전공'), ('선전', '선택전공'), ('응전', '응용전공'), ('계필', '계열필수'), ('일선', '일반선택')], max_length=25),
        ),
    ]
