# Generated by Django 2.0.7 on 2018-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0009_auto_20180719_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='major',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(default=None, on_delete=True, to='webcrawler.Major'),
            preserve_default=False,
        ),
    ]
