# Generated by Django 2.0.7 on 2018-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0011_subject_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_grade',
            field=models.CharField(max_length=10),
        ),
    ]
