# Generated by Django 2.0.7 on 2018-07-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0012_auto_20180719_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(on_delete=True, to='webcrawler.Major', verbose_name='학과'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_detail_major',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=30, verbose_name='제목'),
        ),
    ]
