# Generated by Django 2.0.7 on 2018-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0013_auto_20180719_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('인필교', '인필교'), ('인선교', '인선교'), ('인선전', '인선전'), ('인필전', '인필전'), ('인필BSM', '인필BSM')], max_length=25, verbose_name='공학인증 타입'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='necessary',
            field=models.BooleanField(default=False, verbose_name='필수과목'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_detail_major',
            field=models.CharField(blank=True, max_length=30, verbose_name='세부전공'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_grade',
            field=models.CharField(max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_number',
            field=models.IntegerField(verbose_name='학수번호'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_point',
            field=models.IntegerField(verbose_name='학점'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_theory',
            field=models.CharField(max_length=10, verbose_name='이론'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_training',
            field=models.CharField(max_length=10, verbose_name='실습'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('교필', '교양필수'), ('교선', '교양선택'), ('기전', '기본전공'), ('선전', '선택전공'), ('응전', '응용전공'), ('계필', '계열필수'), ('일선', '일반선택')], max_length=25, verbose_name='과목 유형'),
        ),
    ]
