# Generated by Django 2.0.7 on 2018-07-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0014_auto_20180719_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_semester',
            field=models.IntegerField(default=0, verbose_name='학기'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('교필', '교양필수'), ('교선', '교양선택'), ('기전', '기본전공'), ('선전', '선택전공'), ('응전', '응용전공'), ('계필', '계열필수'), ('일선', '일반선택'), ('전필', '전공필수'), ('전선', '전공선택'), ('교직', '교직')], max_length=25, verbose_name='과목 유형'),
        ),
    ]
