# Generated by Django 2.0.7 on 2018-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0015_auto_20180720_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_year',
            field=models.CharField(default='', max_length=25, verbose_name='학년도'),
            preserve_default=False,
        ),
    ]
