# Generated by Django 2.0.7 on 2018-07-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0016_subject_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrawler.Major', verbose_name='학과'),
        ),
    ]
