# Generated by Django 2.0.7 on 2018-07-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0017_auto_20180721_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_detail_major',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='세부전공'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='학수번호'),
        ),
    ]
