# Generated by Django 2.0.7 on 2018-07-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0018_auto_20180722_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_year',
            field=models.IntegerField(max_length=25, verbose_name='학년도'),
        ),
    ]
