# Generated by Django 2.0.7 on 2018-07-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0019_auto_20180728_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_year',
            field=models.IntegerField(verbose_name='학년도'),
        ),
    ]
