# Generated by Django 2.0.7 on 2018-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0020_auto_20180728_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('교필', '교양필수'), ('교선', '교양선택'), ('기전', '기본전공'), ('선전', '선택전공'), ('응전', '응용전공'), ('계필', '계열필수'), ('일선', '일반선택'), ('전필', '전공필수'), ('전선', '전공선택'), ('교직', '교직'), ('학필', '학필')], max_length=25, verbose_name='과목 유형'),
        ),
    ]
