# Generated by Django 2.0.7 on 2018-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0023_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='eeeee', max_length=20),
            preserve_default=False,
        ),
    ]
    